version: '3.1'

services:

  service:
    image: yisty_webservice
    ports:
      - "3030:3030"
    depends_on:
      - db
    links:
      - db
    volumes:
      - "./src/:/usr/src/app/src/"
    environment:
      POSTGRES_DB: yisty
      POSTGRES_PASSWORD: drowssap
      POSTGRES_USER: postgres

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yisty
      POSTGRES_PASSWORD: drowssap
      POSTGRES_USER: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
