version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: drowssap

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
